DefualtRepoter.format_exception: print also exception class name
The message of an exception is often not enough to get the problem. Print
therefore also the exception class name.